name: data-check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-in-matrix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ipfs:
          - 0.6
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }} with IPFS ${{ matrix.ipfs }}
    steps:
      - name: Set up IPFS ${{ matrix.ipfs }}
        uses: ibnesayeed/setup-ipfs@master
        id: ipfs_setup
        with:
          ipfs_version: ${{ matrix.ipfs }}
          run_daemon: true
      - name: Test IPFS ${{ steps.ipfs_setup.outputs.resolved_ipfs_version }} CLI and API
        shell: bash
        run: |
          set -o pipefail
          ipfs cat /ipfs/QmTBdkekrUFAFtTv9LwGrsiMTriMztqQyofiEdtYsswBBm 
          ipfs cat /ipfs/QmPuAmU4cRWKmJZcQ6SBBhGRiCvq3fmQ64ujPHEJFrE1Mw